import type { Metadata } from 'next';

export const siteConfig: Metadata = {
  title: 'Codart',
  description: 'Welcome to my full stack Next.js 14 space portfolio.',
  keywords: [
    'reactjs',
    'nextjs',
    'vercel',
    'react',
    'space-portfolio',
    'portfolio',
    'react-icons',
    'cn',
    'clsx',
    '3d-portfolio',
    '3d-website',
    'sonner',
    'framer-motion',
    'motion',
    'animation',
    'heroicons',
    'next-themes',
    'postcss',
    'prettier',
    'react-dom',
    'tailwindcss',
    'tailwindcss-animate',
    'ui/ux',
    'js',
    'javascript',
    'typescript',
    'eslint',
    'html',
    'css',
  ] as Array<string>,
  authors: {
    name: 'Mohammad Yahfoufi',
    url: 'https://github.com/MohammadYahfoufi',
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon.png', type: 'image/png' },
      { url: '/icon.png', type: 'image/png' },
    ],
    apple: [
      { url: '/icon.png', sizes: '180x180', type: 'image/png' },
    ],
  },
} as const;
